FROM ubi8/ubi:8.3
MAINTAINER bergvdm <martin.van.den.berg@rivm.nl>
LABEL description="A custom Apache container based on UBI 8"
RUN yum install -y httpd && \
    yum clean all
RUN echo "Hello from Containerfile" > /var/www/html/index.html
CMD ["httpd", "-D", "FOREGROUND"]
